POST localhost:8081/login
Content-Type: application/json

{
  "login": "john",
  "password": "john"
}

###
POST localhost:8081/login
Content-Type: application/json

{
  "login": "",
  "password": "john"
}

###
GET localhost:8081/list?limit=3
auth-token: Bearer eyJraWQiOiIyMTU5YTU3Zi01ZTVhLTRjMWMtOTZkNi0yOGQ0MzQzMTU1ZmEiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huIiwic2NwIjoiZmlsZXMiLCJpc3MiOiJleGFtcGxlLmNvbSIsImV4cCI6MTYxOTcxOTYyNn0.b3b2K19VTk-UVAYw2XtsPmtRT2n2G-8yqslY8hkkPJY-EdrG-2P9vJQqWh1MBlh6zy6bwUTJ4UPbj8YxPh3NTSk-ds9DwlYs7s7w0dTD3qqDfOGtNWGOzTvbzTNBzvHoisBB-mpj87YRph8Yx76SWQ1qkFzx_RDD-qtpd4whcY1wvUdndvxvKwBbDq29UkoA03EWeWS2a0ZdlilhPtQlFzjTmwVhd9kyGGDWmW-wbO4qIpdijNTro7BX1jwwitccwZFobY6oUJz6Qox8V9aWPkuMwGo8MU_ozJMw97dzJuktWHnkJ6RBOVxfuGh4rwsP7uWOYL-RkwnoJIybdwsjHw

###
POST localhost:8081/logout
auth-token: Bearer eyJraWQiOiIyZTZiYzVlYi05N2NlLTRlY2EtOTBhZC1hYWIzY2FjMTM3MDciLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huIiwic2NwIjoiZmlsZXMiLCJpc3MiOiJleGFtcGxlLmNvbSIsImV4cCI6MTYxOTcxMTg2NH0.a5_eaFYovTuOWRRXugYKQ8rNY4Uh5mqH7EoiXsEfh_xVaPeP9H5arE97gxkjMFB32PSyGZhSlxxFI-9uvT2nC0N35y8gvqLpHo6kG4_PKuJQ3ABeYc13_nhV_zNrM7A3TMRATPdVB18ajdE9DE5Pj8TyNzUGin_OMloITKq0OfsvDxUby5pTFL08oWqriQLQfawhwOexORuFNHYsXPerN62mhgzpxU34QR8Npf936JACIrwFd-aZo5dAF2p34PmQpzzkYnsRViaD8ddSOv5NPAGvy7jUmZcxXN4-fEHVRIG8HttdfW9cJx285K3TQK3jOul3HOs6vYV7wSSdSp4gWA

###
DELETE localhost:8081/file
auth-token: Bearer eyJraWQiOiIyNjlkZjQxNi0xZmQxLTRkYWYtYjJhNS0xOTY3NGQyNGI5YjgiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huIiwic2NwIjoiRklMRVMiLCJpc3MiOiJleGFtcGxlLmNvbSIsImV4cCI6MTYxOTY5OTExOH0.kDDctw80pPFDWs6p4lkkOTsDyU00FISjKdhEqz-_kQ1ebhmgC8YEdxw8zHnAZUC7ssI2R6IvehK0rWO5v0lrQRVzmRmzP_zM7sTbMpnXsPdj5Q0ODPSVnamRJrKzuOqsVL6GIrSfONMSIxUqGN8d31zT7sL259zm-U9AoKUZ8fTVpRe7zvR8ijq9JwjY73LdvzJGFaQNvj0Kqd_UCBtLTH-hJg2XWdamKYbiH_7t-34of3DgRbV9sFb0kPPKfRezX81L0HpwlgIIHQr9Wf6cPtbnw78fjXWPvcGQMdUSlZk_fTq0_2MzSB_VUnLlKQAO-0XSRaXUNiPP0JK8KmmN5g

###
PUT localhost:8081/file
auth-token: Bearer eyJraWQiOiIyNjlkZjQxNi0xZmQxLTRkYWYtYjJhNS0xOTY3NGQyNGI5YjgiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huIiwic2NwIjoiRklMRVMiLCJpc3MiOiJleGFtcGxlLmNvbSIsImV4cCI6MTYxOTY5OTExOH0.kDDctw80pPFDWs6p4lkkOTsDyU00FISjKdhEqz-_kQ1ebhmgC8YEdxw8zHnAZUC7ssI2R6IvehK0rWO5v0lrQRVzmRmzP_zM7sTbMpnXsPdj5Q0ODPSVnamRJrKzuOqsVL6GIrSfONMSIxUqGN8d31zT7sL259zm-U9AoKUZ8fTVpRe7zvR8ijq9JwjY73LdvzJGFaQNvj0Kqd_UCBtLTH-hJg2XWdamKYbiH_7t-34of3DgRbV9sFb0kPPKfRezX81L0HpwlgIIHQr9Wf6cPtbnw78fjXWPvcGQMdUSlZk_fTq0_2MzSB_VUnLlKQAO-0XSRaXUNiPP0JK8KmmN5g

###
POST localhost:8081/file?filename=file
auth-token: Bearer eyJraWQiOiIyNjlkZjQxNi0xZmQxLTRkYWYtYjJhNS0xOTY3NGQyNGI5YjgiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huIiwic2NwIjoiRklMRVMiLCJpc3MiOiJleGFtcGxlLmNvbSIsImV4cCI6MTYxOTY5OTExOH0.kDDctw80pPFDWs6p4lkkOTsDyU00FISjKdhEqz-_kQ1ebhmgC8YEdxw8zHnAZUC7ssI2R6IvehK0rWO5v0lrQRVzmRmzP_zM7sTbMpnXsPdj5Q0ODPSVnamRJrKzuOqsVL6GIrSfONMSIxUqGN8d31zT7sL259zm-U9AoKUZ8fTVpRe7zvR8ijq9JwjY73LdvzJGFaQNvj0Kqd_UCBtLTH-hJg2XWdamKYbiH_7t-34of3DgRbV9sFb0kPPKfRezX81L0HpwlgIIHQr9Wf6cPtbnw78fjXWPvcGQMdUSlZk_fTq0_2MzSB_VUnLlKQAO-0XSRaXUNiPP0JK8KmmN5g