name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar for docker image
        run: ./gradlew build -x test --no-daemon --info
      - name: Docker image for tests
        run: docker build -t fjd_cloudservice .
      - name: Build with Gradle
        run: ./gradlew build --info